// This file has been autogenerated.

var profile = require('../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '00977cdb-163f-435f-9c32-39ec8ae61f4d',
    name: 'node',
    username: 'user@domain.example',
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    registeredProviders: ['sqlserver', 'website'],
    registeredResourceNamespaces: ['successbricks.cleardb', 'microsoft.insights', 'successbricks.cleardb', 'microsoft.insights', 'microsoft.web', 'microsoft.visualstudio', 'microsoft.web'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_ARM_TEST_LOCATION'] = 'West US';
  process.env['AZURE_ARM_TEST_SQL_RESOURCE_LOCATION'] = 'West US';
  process.env['AZURE_ARM_TEST_WEBSITES_RESOURCE_LOCATION'] = 'South Central US';
}

exports.scopes = [[function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7275?api-version=2014-04-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xTestResource7275' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31995',
  'x-ms-request-id': '8ee4b829-3767-4a82-9679-36a59313dafe',
  'x-ms-correlation-request-id': '8ee4b829-3767-4a82-9679-36a59313dafe',
  'x-ms-routing-request-id': 'WESTUS:20140905T170923Z:8ee4b829-3767-4a82-9679-36a59313dafe',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:22 GMT',
  'content-length': '109' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7275?api-version=2014-04-01-preview', '*')
  .reply(201, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource7275\",\"name\":\"xTestResource7275\",\"location\":\"westus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-request-id': '2062823d-9874-4239-bce0-28dbdd25a766',
  'x-ms-correlation-request-id': '2062823d-9874-4239-bce0-28dbdd25a766',
  'x-ms-routing-request-id': 'WESTUS:20140905T170923Z:2062823d-9874-4239-bce0-28dbdd25a766',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:23 GMT',
  'content-length': '197' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7275/providers/Microsoft.Web//sites/xTestGrpRes5445?api-version=2014-04-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"Resource not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '1efff287-87da-4767-83ae-04e4bb364484',
  'x-ms-correlation-request-id': '1efff287-87da-4767-83ae-04e4bb364484',
  'x-ms-routing-request-id': 'WESTUS:20140905T170924Z:1efff287-87da-4767-83ae-04e4bb364484',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:24 GMT',
  'content-length': '69' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7275/providers/Microsoft.Web//sites/xTestGrpRes5445?api-version=2014-04-01', '*')
  .reply(200, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource7275/providers/Microsoft.Web/sites/xTestGrpRes5445\",\"name\":\"xTestGrpRes5445\",\"type\":\"Microsoft.Web/sites\",\"location\":\"South Central US\",\"tags\":{},\"properties\":{\"name\":\"xTestGrpRes5445\",\"state\":\"Running\",\"hostNames\":[\"xtestgrpres5445.azurewebsites.net\"],\"webSpace\":\"xTestResource7275-SouthCentralUSwebspace\",\"selfLink\":\"https://waws-prod-sn1-001.api.azurewebsites.windows.net:454/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/webspaces/xTestResource7275-SouthCentralUSwebspace/sites/xTestGrpRes5445\",\"repositorySiteName\":\"xTestGrpRes5445\",\"owner\":null,\"usageState\":0,\"enabled\":true,\"adminEnabled\":true,\"enabledHostNames\":[\"xtestgrpres5445.azurewebsites.net\",\"xtestgrpres5445.scm.azurewebsites.net\"],\"siteProperties\":{\"metadata\":null,\"properties\":[],\"appSettings\":null},\"availabilityState\":0,\"sslCertificates\":null,\"csrs\":[],\"cers\":null,\"siteMode\":null,\"hostNameSslStates\":[{\"name\":\"xtestgrpres5445.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0},{\"name\":\"xtestgrpres5445.scm.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0}],\"computeMode\":null,\"serverFarm\":\"Default1\",\"webHostingPlan\":\"Default1\",\"lastModifiedTimeUtc\":\"2014-09-05T17:09:27.767\",\"storageRecoveryDefaultState\":\"Running\",\"contentAvailabilityState\":0,\"runtimeAvailabilityState\":0,\"siteConfig\":null,\"deploymentId\":\"xTestGrpRes5445\",\"trafficManagerHostNames\":null,\"sku\":\"Free\",\"premiumAppDeployed\":null,\"scmSiteAlsoStopped\":false}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1693',
  'content-type': 'application/json',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-request-id': '60920af7-370c-4a86-ac0c-33512482407a',
  server: 'Microsoft-IIS/8.0',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': 'b92010ac-c37f-466e-ba09-84e2cffef223',
  'x-ms-routing-request-id': 'WESTUS:20140905T170930Z:b92010ac-c37f-466e-ba09-84e2cffef223',
  date: 'Fri, 05 Sep 2014 17:09:30 GMT' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7275?api-version=2014-04-01-preview')
  .reply(200, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource7275\",\"name\":\"xTestResource7275\",\"location\":\"westus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31910',
  'x-ms-request-id': '55b01d5c-ab6f-47f2-86e9-52d84fc46995',
  'x-ms-correlation-request-id': '55b01d5c-ab6f-47f2-86e9-52d84fc46995',
  'x-ms-routing-request-id': 'WESTUS:20140905T170931Z:55b01d5c-ab6f-47f2-86e9-52d84fc46995',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:31 GMT',
  'content-length': '197' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource7275/resources?api-version=2014-04-01-preview')
  .reply(200, "{\"value\":[{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource7275/providers/Microsoft.Web/sites/xTestGrpRes5445\",\"name\":\"xTestGrpRes5445\",\"type\":\"Microsoft.Web/sites\",\"location\":\"southcentralus\",\"tags\":{}}]}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31918',
  'x-ms-request-id': 'd7d619b7-14fc-4caa-a370-0ba76558b870',
  'x-ms-correlation-request-id': 'd7d619b7-14fc-4caa-a370-0ba76558b870',
  'x-ms-routing-request-id': 'WESTUS:20140905T170931Z:d7d619b7-14fc-4caa-a370-0ba76558b870',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:31 GMT',
  'content-length': '243' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7275/providers/Microsoft.Authorization/permissions?api-version=2014-07-01-preview')
  .reply(200, "{\"value\":[{\"actions\":[\"*\"],\"notActions\":[]}]}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31994',
  'x-ms-request-id': 'dbce4da3-7578-4319-9a60-439cfda5fe1e',
  'x-ms-correlation-request-id': 'dbce4da3-7578-4319-9a60-439cfda5fe1e',
  'x-ms-routing-request-id': 'WESTUS:20140905T170932Z:dbce4da3-7578-4319-9a60-439cfda5fe1e',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:32 GMT',
  'content-length': '45' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .delete('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7275?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNzI3NS1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-writes': '1196',
  'x-ms-request-id': '8612e055-055e-40fc-8f8f-ff0042e8e0fb',
  'x-ms-correlation-request-id': '8612e055-055e-40fc-8f8f-ff0042e8e0fb',
  'x-ms-routing-request-id': 'WESTUS:20140905T170933Z:8612e055-055e-40fc-8f8f-ff0042e8e0fb',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:32 GMT',
  'content-length': '0' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNzI3NS1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNzI3NS1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-reads': '31909',
  'x-ms-request-id': '5f8a1106-4242-490f-a884-7ed864bb1a18',
  'x-ms-correlation-request-id': '5f8a1106-4242-490f-a884-7ed864bb1a18',
  'x-ms-routing-request-id': 'WESTUS:20140905T170948Z:5f8a1106-4242-490f-a884-7ed864bb1a18',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:48 GMT',
  'content-length': '0' });
 return result; }],
[function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource9261/providers/Microsoft.Web//sites/xTestGrpRes7549?api-version=2014-04-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xTestResource9261' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '49116714-7a39-49c9-b1e9-bf677c974ae4',
  'x-ms-correlation-request-id': '49116714-7a39-49c9-b1e9-bf677c974ae4',
  'x-ms-routing-request-id': 'WESTUS:20140905T170949Z:49116714-7a39-49c9-b1e9-bf677c974ae4',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:48 GMT',
  'content-length': '109' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource9261/providers/Microsoft.Web//sites/xTestGrpRes7549?api-version=2014-04-01', '*')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xTestResource9261' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'c562f554-1b7b-484a-abd6-d86f22fb8d2b',
  'x-ms-correlation-request-id': 'c562f554-1b7b-484a-abd6-d86f22fb8d2b',
  'x-ms-routing-request-id': 'WESTUS:20140905T170949Z:c562f554-1b7b-484a-abd6-d86f22fb8d2b',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:49 GMT',
  'content-length': '109' });
 return result; }],
[function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource1548?api-version=2014-04-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xTestResource1548' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31993',
  'x-ms-request-id': 'ea725f77-0d46-4cfc-ab76-2e074a305bab',
  'x-ms-correlation-request-id': 'ea725f77-0d46-4cfc-ab76-2e074a305bab',
  'x-ms-routing-request-id': 'WESTUS:20140905T170950Z:ea725f77-0d46-4cfc-ab76-2e074a305bab',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:49 GMT',
  'content-length': '109' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource1548?api-version=2014-04-01-preview', '*')
  .reply(201, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource1548\",\"name\":\"xTestResource1548\",\"location\":\"southcentralus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1196',
  'x-ms-request-id': 'ac18fe10-3ce8-4973-8e0e-d11267cf969b',
  'x-ms-correlation-request-id': 'ac18fe10-3ce8-4973-8e0e-d11267cf969b',
  'x-ms-routing-request-id': 'WESTUS:20140905T170951Z:ac18fe10-3ce8-4973-8e0e-d11267cf969b',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:51 GMT',
  'content-length': '205' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource1548/providers/Microsoft.Web//sites/xTestGrpRes8088?api-version=2014-04-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"Resource not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'b6f0328a-646f-47a2-8497-eed9b5e4a8b6',
  'x-ms-correlation-request-id': 'b6f0328a-646f-47a2-8497-eed9b5e4a8b6',
  'x-ms-routing-request-id': 'WESTUS:20140905T170952Z:b6f0328a-646f-47a2-8497-eed9b5e4a8b6',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:09:51 GMT',
  'content-length': '69' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource1548/providers/Microsoft.Web//sites/xTestGrpRes8088?api-version=2014-04-01', '*')
  .reply(200, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource1548/providers/Microsoft.Web/sites/xTestGrpRes8088\",\"name\":\"xTestGrpRes8088\",\"type\":\"Microsoft.Web/sites\",\"location\":\"South Central US\",\"tags\":{},\"properties\":{\"name\":\"xTestGrpRes8088\",\"state\":\"Running\",\"hostNames\":[\"xtestgrpres8088.azurewebsites.net\"],\"webSpace\":\"xTestResource1548-SouthCentralUSwebspace\",\"selfLink\":\"https://waws-prod-sn1-001.api.azurewebsites.windows.net:454/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/webspaces/xTestResource1548-SouthCentralUSwebspace/sites/xTestGrpRes8088\",\"repositorySiteName\":\"xTestGrpRes8088\",\"owner\":null,\"usageState\":0,\"enabled\":true,\"adminEnabled\":true,\"enabledHostNames\":[\"xtestgrpres8088.azurewebsites.net\",\"xtestgrpres8088.scm.azurewebsites.net\"],\"siteProperties\":{\"metadata\":null,\"properties\":[],\"appSettings\":null},\"availabilityState\":0,\"sslCertificates\":null,\"csrs\":[],\"cers\":null,\"siteMode\":null,\"hostNameSslStates\":[{\"name\":\"xtestgrpres8088.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0},{\"name\":\"xtestgrpres8088.scm.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0}],\"computeMode\":null,\"serverFarm\":\"Default1\",\"webHostingPlan\":\"Default1\",\"lastModifiedTimeUtc\":\"2014-09-05T17:09:56.353\",\"storageRecoveryDefaultState\":\"Running\",\"contentAvailabilityState\":0,\"runtimeAvailabilityState\":0,\"siteConfig\":null,\"deploymentId\":\"xTestGrpRes8088\",\"trafficManagerHostNames\":null,\"sku\":\"Free\",\"premiumAppDeployed\":null,\"scmSiteAlsoStopped\":false}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1693',
  'content-type': 'application/json',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-request-id': 'ad0d2a74-7ca1-4856-906d-2940964e3734',
  server: 'Microsoft-IIS/8.0',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': '06f44b1f-152d-4ea2-ab76-28722f2c9cf5',
  'x-ms-routing-request-id': 'WESTUS:20140905T170959Z:06f44b1f-152d-4ea2-ab76-28722f2c9cf5',
  date: 'Fri, 05 Sep 2014 17:09:58 GMT' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource1548/providers/Microsoft.Web//sites/xTestGrpRes8088?api-version=2014-04-01')
  .reply(200, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource1548/providers/Microsoft.Web/sites/xTestGrpRes8088\",\"name\":\"xTestGrpRes8088\",\"type\":\"Microsoft.Web/sites\",\"location\":\"South Central US\",\"tags\":{},\"properties\":{\"name\":\"xTestGrpRes8088\",\"state\":\"Running\",\"hostNames\":[\"xtestgrpres8088.azurewebsites.net\"],\"webSpace\":\"xTestResource1548-SouthCentralUSwebspace\",\"selfLink\":\"https://waws-prod-sn1-001.api.azurewebsites.windows.net:454/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/webspaces/xTestResource1548-SouthCentralUSwebspace/sites/xTestGrpRes8088\",\"repositorySiteName\":\"xTestGrpRes8088\",\"owner\":null,\"usageState\":0,\"enabled\":true,\"adminEnabled\":true,\"enabledHostNames\":[\"xtestgrpres8088.azurewebsites.net\",\"xtestgrpres8088.scm.azurewebsites.net\"],\"siteProperties\":{\"metadata\":null,\"properties\":[],\"appSettings\":null},\"availabilityState\":0,\"sslCertificates\":null,\"csrs\":[],\"cers\":null,\"siteMode\":null,\"hostNameSslStates\":[{\"name\":\"xtestgrpres8088.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0},{\"name\":\"xtestgrpres8088.scm.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0}],\"computeMode\":null,\"serverFarm\":\"Default1\",\"webHostingPlan\":\"Default1\",\"lastModifiedTimeUtc\":\"2014-09-05T17:09:56.353\",\"storageRecoveryDefaultState\":\"Running\",\"contentAvailabilityState\":0,\"runtimeAvailabilityState\":0,\"siteConfig\":null,\"deploymentId\":\"xTestGrpRes8088\",\"trafficManagerHostNames\":null,\"sku\":\"Free\",\"premiumAppDeployed\":null,\"scmSiteAlsoStopped\":false}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1693',
  'content-type': 'application/json',
  expires: '-1',
  etag: '"1CFC92C377A2710"',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-request-id': '4a6356d4-7a80-4fef-a1cb-262bd99ed74b',
  server: 'Microsoft-IIS/8.0',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '31993',
  'x-ms-correlation-request-id': 'd2d9c92f-dc6d-4bbb-b442-69da9637bc68',
  'x-ms-routing-request-id': 'WESTUS:20140905T170959Z:d2d9c92f-dc6d-4bbb-b442-69da9637bc68',
  date: 'Fri, 05 Sep 2014 17:09:59 GMT' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .delete('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource1548/providers/Microsoft.Web//sites/xTestGrpRes8088?api-version=2014-04-01')
  .reply(200, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  etag: '"1CFC92C377A2710"',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-request-id': 'c4600618-c097-40b9-ae42-066d4f892a14',
  server: 'Microsoft-IIS/8.0',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1195',
  'x-ms-correlation-request-id': 'ff28b300-8754-4be5-b02e-11711b3de486',
  'x-ms-routing-request-id': 'WESTUS:20140905T171003Z:ff28b300-8754-4be5-b02e-11711b3de486',
  date: 'Fri, 05 Sep 2014 17:10:02 GMT' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource1548?api-version=2014-04-01-preview')
  .reply(200, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource1548\",\"name\":\"xTestResource1548\",\"location\":\"southcentralus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31992',
  'x-ms-request-id': '52f82e73-ef30-428d-b347-12fe309f47fa',
  'x-ms-correlation-request-id': '52f82e73-ef30-428d-b347-12fe309f47fa',
  'x-ms-routing-request-id': 'WESTUS:20140905T171004Z:52f82e73-ef30-428d-b347-12fe309f47fa',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:04 GMT',
  'content-length': '205' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource1548/resources?api-version=2014-04-01-preview')
  .reply(200, "{\"value\":[]}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31991',
  'x-ms-request-id': '6794af7d-4013-4f10-9750-a3e01cfefed4',
  'x-ms-correlation-request-id': '6794af7d-4013-4f10-9750-a3e01cfefed4',
  'x-ms-routing-request-id': 'WESTUS:20140905T171004Z:6794af7d-4013-4f10-9750-a3e01cfefed4',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:04 GMT',
  'content-length': '12' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource1548/providers/Microsoft.Authorization/permissions?api-version=2014-07-01-preview')
  .reply(200, "{\"value\":[{\"actions\":[\"*\"],\"notActions\":[]}]}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31908',
  'x-ms-request-id': '83c7c4c5-ebd7-4e76-afa6-f2a8ddd128d1',
  'x-ms-correlation-request-id': '83c7c4c5-ebd7-4e76-afa6-f2a8ddd128d1',
  'x-ms-routing-request-id': 'WESTUS:20140905T171005Z:83c7c4c5-ebd7-4e76-afa6-f2a8ddd128d1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:05 GMT',
  'content-length': '45' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .delete('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource1548?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFMTU0OC1TT1VUSENFTlRSQUxVUyIsImpvYkxvY2F0aW9uIjoic291dGhjZW50cmFsdXMifQ==?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-writes': '1195',
  'x-ms-request-id': '3368eb77-9986-40dd-8263-433d94fa7405',
  'x-ms-correlation-request-id': '3368eb77-9986-40dd-8263-433d94fa7405',
  'x-ms-routing-request-id': 'WESTUS:20140905T171006Z:3368eb77-9986-40dd-8263-433d94fa7405',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:06 GMT',
  'content-length': '0' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFMTU0OC1TT1VUSENFTlRSQUxVUyIsImpvYkxvY2F0aW9uIjoic291dGhjZW50cmFsdXMifQ==?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFMTU0OC1TT1VUSENFTlRSQUxVUyIsImpvYkxvY2F0aW9uIjoic291dGhjZW50cmFsdXMifQ==?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-reads': '31990',
  'x-ms-request-id': '21d12201-5dc7-448d-830b-0a4164ed3a7a',
  'x-ms-correlation-request-id': '21d12201-5dc7-448d-830b-0a4164ed3a7a',
  'x-ms-routing-request-id': 'WESTUS:20140905T171022Z:21d12201-5dc7-448d-830b-0a4164ed3a7a',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:21 GMT',
  'content-length': '0' });
 return result; }],
[function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource2121?api-version=2014-04-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xTestResource2121' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31992',
  'x-ms-request-id': '3e1fb132-6836-4cab-bf8d-7c886e619bdb',
  'x-ms-correlation-request-id': '3e1fb132-6836-4cab-bf8d-7c886e619bdb',
  'x-ms-routing-request-id': 'WESTUS:20140905T171022Z:3e1fb132-6836-4cab-bf8d-7c886e619bdb',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:22 GMT',
  'content-length': '109' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource2121?api-version=2014-04-01-preview', '*')
  .reply(201, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource2121\",\"name\":\"xTestResource2121\",\"location\":\"westus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-request-id': '55db84e1-79ab-4cad-bd73-3f3bb934ff91',
  'x-ms-correlation-request-id': '55db84e1-79ab-4cad-bd73-3f3bb934ff91',
  'x-ms-routing-request-id': 'WESTUS:20140905T171023Z:55db84e1-79ab-4cad-bd73-3f3bb934ff91',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:23 GMT',
  'content-length': '197' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource2121/providers/Microsoft.Web//sites/xTestGrpRes9012?api-version=2014-04-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"Resource not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'd1654772-211c-4334-af9c-9e3a5bfa7666',
  'x-ms-correlation-request-id': 'd1654772-211c-4334-af9c-9e3a5bfa7666',
  'x-ms-routing-request-id': 'WESTUS:20140905T171023Z:d1654772-211c-4334-af9c-9e3a5bfa7666',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:23 GMT',
  'content-length': '69' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource2121/providers/Microsoft.Web//sites/xTestGrpRes9012?api-version=2014-04-01', '*')
  .reply(200, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource2121/providers/Microsoft.Web/sites/xTestGrpRes9012\",\"name\":\"xTestGrpRes9012\",\"type\":\"Microsoft.Web/sites\",\"location\":\"South Central US\",\"tags\":{},\"properties\":{\"name\":\"xTestGrpRes9012\",\"state\":\"Running\",\"hostNames\":[\"xtestgrpres9012.azurewebsites.net\"],\"webSpace\":\"xTestResource2121-SouthCentralUSwebspace\",\"selfLink\":\"https://waws-prod-sn1-001.api.azurewebsites.windows.net:454/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/webspaces/xTestResource2121-SouthCentralUSwebspace/sites/xTestGrpRes9012\",\"repositorySiteName\":\"xTestGrpRes9012\",\"owner\":null,\"usageState\":0,\"enabled\":true,\"adminEnabled\":true,\"enabledHostNames\":[\"xtestgrpres9012.azurewebsites.net\",\"xtestgrpres9012.scm.azurewebsites.net\"],\"siteProperties\":{\"metadata\":null,\"properties\":[],\"appSettings\":null},\"availabilityState\":0,\"sslCertificates\":null,\"csrs\":[],\"cers\":null,\"siteMode\":null,\"hostNameSslStates\":[{\"name\":\"xtestgrpres9012.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0},{\"name\":\"xtestgrpres9012.scm.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0}],\"computeMode\":null,\"serverFarm\":\"Default1\",\"webHostingPlan\":\"Default1\",\"lastModifiedTimeUtc\":\"2014-09-05T17:10:27.573\",\"storageRecoveryDefaultState\":\"Running\",\"contentAvailabilityState\":0,\"runtimeAvailabilityState\":0,\"siteConfig\":null,\"deploymentId\":\"xTestGrpRes9012\",\"trafficManagerHostNames\":null,\"sku\":\"Free\",\"premiumAppDeployed\":null,\"scmSiteAlsoStopped\":false}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1693',
  'content-type': 'application/json',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-request-id': '84cfd687-0fe8-4c8a-afff-bbd4348b4d43',
  server: 'Microsoft-IIS/8.0',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1196',
  'x-ms-correlation-request-id': '39545274-f1c0-40fa-bd0f-33c2cdbcb73f',
  'x-ms-routing-request-id': 'WESTUS:20140905T171029Z:39545274-f1c0-40fa-bd0f-33c2cdbcb73f',
  date: 'Fri, 05 Sep 2014 17:10:29 GMT' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource2121/resources?api-version=2014-04-01-preview')
  .reply(200, "{\"value\":[{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource2121/providers/Microsoft.Web/sites/xTestGrpRes9012\",\"name\":\"xTestGrpRes9012\",\"type\":\"Microsoft.Web/sites\",\"location\":\"southcentralus\",\"tags\":{}}]}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31914',
  'x-ms-request-id': '61ab30fa-dc4d-4597-825f-cbd6b413eef0',
  'x-ms-correlation-request-id': '61ab30fa-dc4d-4597-825f-cbd6b413eef0',
  'x-ms-routing-request-id': 'WESTUS:20140905T171029Z:61ab30fa-dc4d-4597-825f-cbd6b413eef0',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:29 GMT',
  'content-length': '243' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .delete('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource2121?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFMjEyMS1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-writes': '1195',
  'x-ms-request-id': '3d3d48da-26cc-4639-a2cd-6552c0d795b9',
  'x-ms-correlation-request-id': '3d3d48da-26cc-4639-a2cd-6552c0d795b9',
  'x-ms-routing-request-id': 'WESTUS:20140905T171030Z:3d3d48da-26cc-4639-a2cd-6552c0d795b9',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:30 GMT',
  'content-length': '0' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFMjEyMS1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFMjEyMS1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-reads': '31913',
  'x-ms-request-id': 'e062219e-a250-4539-a8c6-1663d6907dde',
  'x-ms-correlation-request-id': 'e062219e-a250-4539-a8c6-1663d6907dde',
  'x-ms-routing-request-id': 'WESTUS:20140905T171046Z:e062219e-a250-4539-a8c6-1663d6907dde',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:45 GMT',
  'content-length': '0' });
 return result; }],
[function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource4367?api-version=2014-04-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xTestResource4367' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31989',
  'x-ms-request-id': '508d7c9f-d9fb-4acd-9958-c1197df13170',
  'x-ms-correlation-request-id': '508d7c9f-d9fb-4acd-9958-c1197df13170',
  'x-ms-routing-request-id': 'WESTUS:20140905T171046Z:508d7c9f-d9fb-4acd-9958-c1197df13170',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:46 GMT',
  'content-length': '109' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource4367?api-version=2014-04-01-preview', '*')
  .reply(201, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource4367\",\"name\":\"xTestResource4367\",\"location\":\"westus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-request-id': '3ce667e7-813c-4ecd-a970-77327b9489eb',
  'x-ms-correlation-request-id': '3ce667e7-813c-4ecd-a970-77327b9489eb',
  'x-ms-routing-request-id': 'WESTUS:20140905T171047Z:3ce667e7-813c-4ecd-a970-77327b9489eb',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:47 GMT',
  'content-length': '197' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7579?api-version=2014-04-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xTestResource7579' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31907',
  'x-ms-request-id': '573151ad-703c-42ca-a17c-4fe9d60e5c9e',
  'x-ms-correlation-request-id': '573151ad-703c-42ca-a17c-4fe9d60e5c9e',
  'x-ms-routing-request-id': 'WESTUS:20140905T171048Z:573151ad-703c-42ca-a17c-4fe9d60e5c9e',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:48 GMT',
  'content-length': '109' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7579?api-version=2014-04-01-preview', '*')
  .reply(201, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource7579\",\"name\":\"xTestResource7579\",\"location\":\"westus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1196',
  'x-ms-request-id': '8c3bc6f0-2351-4c45-96df-acac6442c7f1',
  'x-ms-correlation-request-id': '8c3bc6f0-2351-4c45-96df-acac6442c7f1',
  'x-ms-routing-request-id': 'WESTUS:20140905T171048Z:8c3bc6f0-2351-4c45-96df-acac6442c7f1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:48 GMT',
  'content-length': '197' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource4367/providers/Microsoft.Web//sites/xTestGrpRes2884?api-version=2014-04-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"Resource not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '41d6233c-2c81-4ee0-a7d0-746d210a72a5',
  'x-ms-correlation-request-id': '41d6233c-2c81-4ee0-a7d0-746d210a72a5',
  'x-ms-routing-request-id': 'WESTUS:20140905T171049Z:41d6233c-2c81-4ee0-a7d0-746d210a72a5',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:49 GMT',
  'content-length': '69' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource4367/providers/Microsoft.Web//sites/xTestGrpRes2884?api-version=2014-04-01', '*')
  .reply(200, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource4367/providers/Microsoft.Web/sites/xTestGrpRes2884\",\"name\":\"xTestGrpRes2884\",\"type\":\"Microsoft.Web/sites\",\"location\":\"South Central US\",\"tags\":{},\"properties\":{\"name\":\"xTestGrpRes2884\",\"state\":\"Running\",\"hostNames\":[\"xtestgrpres2884.azurewebsites.net\"],\"webSpace\":\"xTestResource4367-SouthCentralUSwebspace\",\"selfLink\":\"https://waws-prod-sn1-001.api.azurewebsites.windows.net:454/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/webspaces/xTestResource4367-SouthCentralUSwebspace/sites/xTestGrpRes2884\",\"repositorySiteName\":\"xTestGrpRes2884\",\"owner\":null,\"usageState\":0,\"enabled\":true,\"adminEnabled\":true,\"enabledHostNames\":[\"xtestgrpres2884.azurewebsites.net\",\"xtestgrpres2884.scm.azurewebsites.net\"],\"siteProperties\":{\"metadata\":null,\"properties\":[],\"appSettings\":null},\"availabilityState\":0,\"sslCertificates\":null,\"csrs\":[],\"cers\":null,\"siteMode\":null,\"hostNameSslStates\":[{\"name\":\"xtestgrpres2884.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0},{\"name\":\"xtestgrpres2884.scm.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0}],\"computeMode\":null,\"serverFarm\":\"Default1\",\"webHostingPlan\":\"Default1\",\"lastModifiedTimeUtc\":\"2014-09-05T17:10:52.94\",\"storageRecoveryDefaultState\":\"Running\",\"contentAvailabilityState\":0,\"runtimeAvailabilityState\":0,\"siteConfig\":null,\"deploymentId\":\"xTestGrpRes2884\",\"trafficManagerHostNames\":null,\"sku\":\"Free\",\"premiumAppDeployed\":null,\"scmSiteAlsoStopped\":false}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1692',
  'content-type': 'application/json',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-request-id': '88e4c902-32ff-438f-99cc-f985c442dd81',
  server: 'Microsoft-IIS/8.0',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1193',
  'x-ms-correlation-request-id': '7937cf19-8efd-4858-8b04-c31d33f04cc3',
  'x-ms-routing-request-id': 'WESTUS:20140905T171055Z:7937cf19-8efd-4858-8b04-c31d33f04cc3',
  date: 'Fri, 05 Sep 2014 17:10:55 GMT' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7579/providers/Microsoft.Web//sites/xTestGrpRes232?api-version=2014-04-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"Resource not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '515119f1-70bd-4c34-a2d0-c97e23b27408',
  'x-ms-correlation-request-id': '515119f1-70bd-4c34-a2d0-c97e23b27408',
  'x-ms-routing-request-id': 'WESTUS:20140905T171056Z:515119f1-70bd-4c34-a2d0-c97e23b27408',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:10:56 GMT',
  'content-length': '69' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7579/providers/Microsoft.Web//sites/xTestGrpRes232?api-version=2014-04-01', '*')
  .reply(200, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource7579/providers/Microsoft.Web/sites/xTestGrpRes232\",\"name\":\"xTestGrpRes232\",\"type\":\"Microsoft.Web/sites\",\"location\":\"South Central US\",\"tags\":{},\"properties\":{\"name\":\"xTestGrpRes232\",\"state\":\"Running\",\"hostNames\":[\"xtestgrpres232.azurewebsites.net\"],\"webSpace\":\"xTestResource7579-SouthCentralUSwebspace\",\"selfLink\":\"https://waws-prod-sn1-001.api.azurewebsites.windows.net:454/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/webspaces/xTestResource7579-SouthCentralUSwebspace/sites/xTestGrpRes232\",\"repositorySiteName\":\"xTestGrpRes232\",\"owner\":null,\"usageState\":0,\"enabled\":true,\"adminEnabled\":true,\"enabledHostNames\":[\"xtestgrpres232.azurewebsites.net\",\"xtestgrpres232.scm.azurewebsites.net\"],\"siteProperties\":{\"metadata\":null,\"properties\":[],\"appSettings\":null},\"availabilityState\":0,\"sslCertificates\":null,\"csrs\":[],\"cers\":null,\"siteMode\":null,\"hostNameSslStates\":[{\"name\":\"xtestgrpres232.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0},{\"name\":\"xtestgrpres232.scm.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0}],\"computeMode\":null,\"serverFarm\":\"Default1\",\"webHostingPlan\":\"Default1\",\"lastModifiedTimeUtc\":\"2014-09-05T17:10:59.583\",\"storageRecoveryDefaultState\":\"Running\",\"contentAvailabilityState\":0,\"runtimeAvailabilityState\":0,\"siteConfig\":null,\"deploymentId\":\"xTestGrpRes232\",\"trafficManagerHostNames\":null,\"sku\":\"Free\",\"premiumAppDeployed\":null,\"scmSiteAlsoStopped\":false}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1682',
  'content-type': 'application/json',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-request-id': '5a85e5b7-ddf0-4721-af14-b2fb52f38c14',
  server: 'Microsoft-IIS/8.0',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1192',
  'x-ms-correlation-request-id': 'e624416a-1cf8-43f9-9567-c1f17bab98e2',
  'x-ms-routing-request-id': 'WESTUS:20140905T171102Z:e624416a-1cf8-43f9-9567-c1f17bab98e2',
  date: 'Fri, 05 Sep 2014 17:11:01 GMT' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource4367/resources?$filter=resourceType%20eq%20%27Microsoft.Web%2Fsites%27&api-version=2014-04-01-preview')
  .reply(200, "{\"value\":[{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource4367/providers/Microsoft.Web/sites/xTestGrpRes2884\",\"name\":\"xTestGrpRes2884\",\"type\":\"Microsoft.Web/sites\",\"location\":\"southcentralus\",\"tags\":{}}]}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31906',
  'x-ms-request-id': '09af8ff5-4a8a-44bf-86ca-e8898583d0d1',
  'x-ms-correlation-request-id': '09af8ff5-4a8a-44bf-86ca-e8898583d0d1',
  'x-ms-routing-request-id': 'WESTUS:20140905T171102Z:09af8ff5-4a8a-44bf-86ca-e8898583d0d1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:11:02 GMT',
  'content-length': '243' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .delete('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource4367?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNDM2Ny1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-writes': '1195',
  'x-ms-request-id': '0fd8e4cb-eb27-43c2-b9ce-2a843f6c0f25',
  'x-ms-correlation-request-id': '0fd8e4cb-eb27-43c2-b9ce-2a843f6c0f25',
  'x-ms-routing-request-id': 'WESTUS:20140905T171103Z:0fd8e4cb-eb27-43c2-b9ce-2a843f6c0f25',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:11:03 GMT',
  'content-length': '0' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNDM2Ny1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNDM2Ny1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-reads': '31986',
  'x-ms-request-id': 'f2142059-a6a5-445d-9627-337b21eb8c10',
  'x-ms-correlation-request-id': 'f2142059-a6a5-445d-9627-337b21eb8c10',
  'x-ms-routing-request-id': 'WESTUS:20140905T171118Z:f2142059-a6a5-445d-9627-337b21eb8c10',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:11:18 GMT',
  'content-length': '0' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .delete('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7579?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNzU3OS1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-writes': '1191',
  'x-ms-request-id': '4282f100-3523-4d58-80ea-993ad2480c4b',
  'x-ms-correlation-request-id': '4282f100-3523-4d58-80ea-993ad2480c4b',
  'x-ms-routing-request-id': 'WESTUS:20140905T171119Z:4282f100-3523-4d58-80ea-993ad2480c4b',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:11:19 GMT',
  'content-length': '0' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNzU3OS1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNzU3OS1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-reads': '31985',
  'x-ms-request-id': '4d70c691-8495-4154-9c61-4d82bab4596b',
  'x-ms-correlation-request-id': '4d70c691-8495-4154-9c61-4d82bab4596b',
  'x-ms-routing-request-id': 'WESTUS:20140905T171134Z:4d70c691-8495-4154-9c61-4d82bab4596b',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:11:34 GMT',
  'content-length': '0' });
 return result; }],
[function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7206?api-version=2014-04-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xTestResource7206' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31991',
  'x-ms-request-id': '1e20fccb-2da8-4905-b400-1161d7861025',
  'x-ms-correlation-request-id': '1e20fccb-2da8-4905-b400-1161d7861025',
  'x-ms-routing-request-id': 'WESTUS:20140905T171135Z:1e20fccb-2da8-4905-b400-1161d7861025',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:11:34 GMT',
  'content-length': '109' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7206?api-version=2014-04-01-preview', '*')
  .reply(201, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource7206\",\"name\":\"xTestResource7206\",\"location\":\"westus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-request-id': '3346aaaa-63bb-4ede-b6ba-48b5dcdb68cd',
  'x-ms-correlation-request-id': '3346aaaa-63bb-4ede-b6ba-48b5dcdb68cd',
  'x-ms-routing-request-id': 'WESTUS:20140905T171136Z:3346aaaa-63bb-4ede-b6ba-48b5dcdb68cd',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:11:36 GMT',
  'content-length': '197' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7206/providers/Microsoft.Web//sites/xTestGrpRes5903?api-version=2014-04-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"Resource not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '78e50576-28ab-407c-86f6-20360e9cd569',
  'x-ms-correlation-request-id': '78e50576-28ab-407c-86f6-20360e9cd569',
  'x-ms-routing-request-id': 'WESTUS:20140905T171136Z:78e50576-28ab-407c-86f6-20360e9cd569',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:11:36 GMT',
  'content-length': '69' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7206/providers/Microsoft.Web//sites/xTestGrpRes5903?api-version=2014-04-01', '*')
  .reply(200, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource7206/providers/Microsoft.Web/sites/xTestGrpRes5903\",\"name\":\"xTestGrpRes5903\",\"type\":\"Microsoft.Web/sites\",\"location\":\"South Central US\",\"tags\":{},\"properties\":{\"name\":\"xTestGrpRes5903\",\"state\":\"Running\",\"hostNames\":[\"xtestgrpres5903.azurewebsites.net\"],\"webSpace\":\"xTestResource7206-SouthCentralUSwebspace\",\"selfLink\":\"https://waws-prod-sn1-001.api.azurewebsites.windows.net:454/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/webspaces/xTestResource7206-SouthCentralUSwebspace/sites/xTestGrpRes5903\",\"repositorySiteName\":\"xTestGrpRes5903\",\"owner\":null,\"usageState\":0,\"enabled\":true,\"adminEnabled\":true,\"enabledHostNames\":[\"xtestgrpres5903.azurewebsites.net\",\"xtestgrpres5903.scm.azurewebsites.net\"],\"siteProperties\":{\"metadata\":null,\"properties\":[],\"appSettings\":null},\"availabilityState\":0,\"sslCertificates\":null,\"csrs\":[],\"cers\":null,\"siteMode\":null,\"hostNameSslStates\":[{\"name\":\"xtestgrpres5903.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0},{\"name\":\"xtestgrpres5903.scm.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0}],\"computeMode\":null,\"serverFarm\":\"Default1\",\"webHostingPlan\":\"Default1\",\"lastModifiedTimeUtc\":\"2014-09-05T17:11:42.737\",\"storageRecoveryDefaultState\":\"Running\",\"contentAvailabilityState\":0,\"runtimeAvailabilityState\":0,\"siteConfig\":null,\"deploymentId\":\"xTestGrpRes5903\",\"trafficManagerHostNames\":null,\"sku\":\"Free\",\"premiumAppDeployed\":null,\"scmSiteAlsoStopped\":false}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1693',
  'content-type': 'application/json',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-request-id': 'd8e50355-8afd-494c-bee7-35d18395d55d',
  server: 'Microsoft-IIS/8.0',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1193',
  'x-ms-correlation-request-id': '1fafc353-eceb-4686-8b40-636e67d3a446',
  'x-ms-routing-request-id': 'WESTUS:20140905T171145Z:1fafc353-eceb-4686-8b40-636e67d3a446',
  date: 'Fri, 05 Sep 2014 17:11:45 GMT' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7206/providers/Microsoft.Web//sites/xTestGrpRes5903?api-version=2014-04-01')
  .reply(200, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource7206/providers/Microsoft.Web/sites/xTestGrpRes5903\",\"name\":\"xTestGrpRes5903\",\"type\":\"Microsoft.Web/sites\",\"location\":\"South Central US\",\"tags\":{},\"properties\":{\"name\":\"xTestGrpRes5903\",\"state\":\"Running\",\"hostNames\":[\"xtestgrpres5903.azurewebsites.net\"],\"webSpace\":\"xTestResource7206-SouthCentralUSwebspace\",\"selfLink\":\"https://waws-prod-sn1-001.api.azurewebsites.windows.net:454/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/webspaces/xTestResource7206-SouthCentralUSwebspace/sites/xTestGrpRes5903\",\"repositorySiteName\":\"xTestGrpRes5903\",\"owner\":null,\"usageState\":0,\"enabled\":true,\"adminEnabled\":true,\"enabledHostNames\":[\"xtestgrpres5903.azurewebsites.net\",\"xtestgrpres5903.scm.azurewebsites.net\"],\"siteProperties\":{\"metadata\":null,\"properties\":[],\"appSettings\":null},\"availabilityState\":0,\"sslCertificates\":null,\"csrs\":[],\"cers\":null,\"siteMode\":null,\"hostNameSslStates\":[{\"name\":\"xtestgrpres5903.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0},{\"name\":\"xtestgrpres5903.scm.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0}],\"computeMode\":null,\"serverFarm\":\"Default1\",\"webHostingPlan\":\"Default1\",\"lastModifiedTimeUtc\":\"2014-09-05T17:11:42.737\",\"storageRecoveryDefaultState\":\"Running\",\"contentAvailabilityState\":0,\"runtimeAvailabilityState\":0,\"siteConfig\":null,\"deploymentId\":\"xTestGrpRes5903\",\"trafficManagerHostNames\":null,\"sku\":\"Free\",\"premiumAppDeployed\":null,\"scmSiteAlsoStopped\":false}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1693',
  'content-type': 'application/json',
  expires: '-1',
  etag: '"1CFC92C76E31010"',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-request-id': '06270697-83bf-4242-94cd-c33e2ea1176f',
  server: 'Microsoft-IIS/8.0',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '31989',
  'x-ms-correlation-request-id': '747122ad-db85-4435-9c5d-5b6a1e353662',
  'x-ms-routing-request-id': 'WESTUS:20140905T171146Z:747122ad-db85-4435-9c5d-5b6a1e353662',
  date: 'Fri, 05 Sep 2014 17:11:46 GMT' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7206/providers/Microsoft.Web//sites/xTestGrpRes5903/providers/Microsoft.Authorization/permissions?api-version=2014-07-01-preview')
  .reply(200, "{\"value\":[{\"actions\":[\"*\"],\"notActions\":[]}]}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31905',
  'x-ms-request-id': '53a2f96b-2719-463e-b0d1-bc10a788d5eb',
  'x-ms-correlation-request-id': '53a2f96b-2719-463e-b0d1-bc10a788d5eb',
  'x-ms-routing-request-id': 'WESTUS:20140905T171146Z:53a2f96b-2719-463e-b0d1-bc10a788d5eb',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:11:46 GMT',
  'content-length': '45' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .delete('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource7206?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNzIwNi1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-request-id': '8166bb55-ac85-4800-8f89-5f33474a1844',
  'x-ms-correlation-request-id': '8166bb55-ac85-4800-8f89-5f33474a1844',
  'x-ms-routing-request-id': 'WESTUS:20140905T171147Z:8166bb55-ac85-4800-8f89-5f33474a1844',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:11:46 GMT',
  'content-length': '0' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNzIwNi1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNzIwNi1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-reads': '31904',
  'x-ms-request-id': 'c5e8c54e-98f6-407f-8288-a6fbc89b5f3a',
  'x-ms-correlation-request-id': 'c5e8c54e-98f6-407f-8288-a6fbc89b5f3a',
  'x-ms-routing-request-id': 'WESTUS:20140905T171202Z:c5e8c54e-98f6-407f-8288-a6fbc89b5f3a',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:12:02 GMT',
  'content-length': '0' });
 return result; }],
[function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource5137?api-version=2014-04-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xTestResource5137' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31912',
  'x-ms-request-id': 'ae01a0ca-0b11-4d59-a221-8dee8f115136',
  'x-ms-correlation-request-id': 'ae01a0ca-0b11-4d59-a221-8dee8f115136',
  'x-ms-routing-request-id': 'WESTUS:20140905T171203Z:ae01a0ca-0b11-4d59-a221-8dee8f115136',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:12:03 GMT',
  'content-length': '109' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource5137?api-version=2014-04-01-preview', '*')
  .reply(201, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource5137\",\"name\":\"xTestResource5137\",\"location\":\"westus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1193',
  'x-ms-request-id': 'b91cbaa7-d6af-4b50-a706-a0c1bd754e09',
  'x-ms-correlation-request-id': 'b91cbaa7-d6af-4b50-a706-a0c1bd754e09',
  'x-ms-routing-request-id': 'WESTUS:20140905T171203Z:b91cbaa7-d6af-4b50-a706-a0c1bd754e09',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:12:03 GMT',
  'content-length': '197' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource5137/providers/Microsoft.Web//sites/xTestGrpRes7575?api-version=2014-04-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"Resource not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'dbcd45e1-1126-4e1d-9bac-e89b4a83d7ed',
  'x-ms-correlation-request-id': 'dbcd45e1-1126-4e1d-9bac-e89b4a83d7ed',
  'x-ms-routing-request-id': 'WESTUS:20140905T171204Z:dbcd45e1-1126-4e1d-9bac-e89b4a83d7ed',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:12:03 GMT',
  'content-length': '69' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource5137/providers/Microsoft.Web//sites/xTestGrpRes7575?api-version=2014-04-01', '*')
  .reply(200, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource5137/providers/Microsoft.Web/sites/xTestGrpRes7575\",\"name\":\"xTestGrpRes7575\",\"type\":\"Microsoft.Web/sites\",\"location\":\"South Central US\",\"tags\":{},\"properties\":{\"name\":\"xTestGrpRes7575\",\"state\":\"Running\",\"hostNames\":[\"xtestgrpres7575.azurewebsites.net\"],\"webSpace\":\"xTestResource5137-SouthCentralUSwebspace\",\"selfLink\":\"https://waws-prod-sn1-001.api.azurewebsites.windows.net:454/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/webspaces/xTestResource5137-SouthCentralUSwebspace/sites/xTestGrpRes7575\",\"repositorySiteName\":\"xTestGrpRes7575\",\"owner\":null,\"usageState\":0,\"enabled\":true,\"adminEnabled\":true,\"enabledHostNames\":[\"xtestgrpres7575.azurewebsites.net\",\"xtestgrpres7575.scm.azurewebsites.net\"],\"siteProperties\":{\"metadata\":null,\"properties\":[],\"appSettings\":null},\"availabilityState\":0,\"sslCertificates\":null,\"csrs\":[],\"cers\":null,\"siteMode\":null,\"hostNameSslStates\":[{\"name\":\"xtestgrpres7575.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0},{\"name\":\"xtestgrpres7575.scm.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0}],\"computeMode\":null,\"serverFarm\":\"Default1\",\"webHostingPlan\":\"Default1\",\"lastModifiedTimeUtc\":\"2014-09-05T17:12:07.497\",\"storageRecoveryDefaultState\":\"Running\",\"contentAvailabilityState\":0,\"runtimeAvailabilityState\":0,\"siteConfig\":null,\"deploymentId\":\"xTestGrpRes7575\",\"trafficManagerHostNames\":null,\"sku\":\"Free\",\"premiumAppDeployed\":null,\"scmSiteAlsoStopped\":false}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1693',
  'content-type': 'application/json',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-request-id': 'f7760bca-4b66-42da-a231-df85043117d1',
  server: 'Microsoft-IIS/8.0',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1192',
  'x-ms-correlation-request-id': '63fa17e8-e78c-4bd7-a4d6-031996f37c29',
  'x-ms-routing-request-id': 'WESTUS:20140905T171210Z:63fa17e8-e78c-4bd7-a4d6-031996f37c29',
  date: 'Fri, 05 Sep 2014 17:12:09 GMT' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource5137/providers/Microsoft.Web//sites/xTestGrpRes7575?api-version=2014-04-01')
  .reply(200, "{\"id\":\"/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/xTestResource5137/providers/Microsoft.Web/sites/xTestGrpRes7575\",\"name\":\"xTestGrpRes7575\",\"type\":\"Microsoft.Web/sites\",\"location\":\"South Central US\",\"tags\":{},\"properties\":{\"name\":\"xTestGrpRes7575\",\"state\":\"Running\",\"hostNames\":[\"xtestgrpres7575.azurewebsites.net\"],\"webSpace\":\"xTestResource5137-SouthCentralUSwebspace\",\"selfLink\":\"https://waws-prod-sn1-001.api.azurewebsites.windows.net:454/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/webspaces/xTestResource5137-SouthCentralUSwebspace/sites/xTestGrpRes7575\",\"repositorySiteName\":\"xTestGrpRes7575\",\"owner\":null,\"usageState\":0,\"enabled\":true,\"adminEnabled\":true,\"enabledHostNames\":[\"xtestgrpres7575.azurewebsites.net\",\"xtestgrpres7575.scm.azurewebsites.net\"],\"siteProperties\":{\"metadata\":null,\"properties\":[],\"appSettings\":null},\"availabilityState\":0,\"sslCertificates\":null,\"csrs\":[],\"cers\":null,\"siteMode\":null,\"hostNameSslStates\":[{\"name\":\"xtestgrpres7575.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0},{\"name\":\"xtestgrpres7575.scm.azurewebsites.net\",\"sslState\":0,\"ipBasedSslResult\":null,\"virtualIP\":null,\"thumbprint\":null,\"toUpdate\":null,\"toUpdateIpBasedSsl\":null,\"ipBasedSslState\":0}],\"computeMode\":null,\"serverFarm\":\"Default1\",\"webHostingPlan\":\"Default1\",\"lastModifiedTimeUtc\":\"2014-09-05T17:12:07.497\",\"storageRecoveryDefaultState\":\"Running\",\"contentAvailabilityState\":0,\"runtimeAvailabilityState\":0,\"siteConfig\":null,\"deploymentId\":\"xTestGrpRes7575\",\"trafficManagerHostNames\":null,\"sku\":\"Free\",\"premiumAppDeployed\":null,\"scmSiteAlsoStopped\":false}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1693',
  'content-type': 'application/json',
  expires: '-1',
  etag: '"1CFC92C85A52390"',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-request-id': 'cf3f2cab-b62c-42b3-b8e3-8e89b18e0278',
  server: 'Microsoft-IIS/8.0',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '31987',
  'x-ms-correlation-request-id': '0190ef9f-46db-425e-86d6-8afcdb990a5c',
  'x-ms-routing-request-id': 'WESTUS:20140905T171210Z:0190ef9f-46db-425e-86d6-8afcdb990a5c',
  date: 'Fri, 05 Sep 2014 17:12:10 GMT' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource5137/providers/Microsoft.Web//sites/xTestGrpRes7575/providers/Microsoft.Authorization/permissions?api-version=2014-07-01-preview')
  .reply(200, "{\"value\":[{\"actions\":[\"*\"],\"notActions\":[]}]}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '31903',
  'x-ms-request-id': '4cf55e64-b202-4283-b892-64b483619b53',
  'x-ms-correlation-request-id': '4cf55e64-b202-4283-b892-64b483619b53',
  'x-ms-routing-request-id': 'WESTUS:20140905T171211Z:4cf55e64-b202-4283-b892-64b483619b53',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:12:11 GMT',
  'content-length': '45' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .delete('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourcegroups/xTestResource5137?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNTEzNy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-writes': '1193',
  'x-ms-request-id': 'fffc7edf-e703-49f2-acfd-75ac74de9233',
  'x-ms-correlation-request-id': 'fffc7edf-e703-49f2-acfd-75ac74de9233',
  'x-ms-routing-request-id': 'WESTUS:20140905T171211Z:fffc7edf-e703-49f2-acfd-75ac74de9233',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:12:11 GMT',
  'content-length': '0' });
 return result; },
function (nock) {
var result =
nock('https://management.azure.com:443')
  .get('/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNTEzNy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1YVEVTVFJFU09VUkNFNTEzNy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2014-04-01-preview',
  'retry-after': '15',
  'x-ms-ratelimit-remaining-subscription-reads': '31984',
  'x-ms-request-id': '23d06799-8f83-44e6-a0ff-83b095d37273',
  'x-ms-correlation-request-id': '23d06799-8f83-44e6-a0ff-83b095d37273',
  'x-ms-routing-request-id': 'WESTUS:20140905T171227Z:23d06799-8f83-44e6-a0ff-83b095d37273',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 05 Sep 2014 17:12:27 GMT',
  'content-length': '0' });
 return result; }]];
 exports.randomTestIdsGenerated = function() { return ['xTestResource7275','xTestGrpRes5445','xTestResource9261','xTestGrpRes7549','xTestResource1548','xTestGrpRes8088','xTestResource2121','xTestGrpRes9012','xTestResource4367','xTestGrpRes2884','xTestResource7579','xTestGrpRes232','xTestResource7206','xTestGrpRes5903','xTestResource5137','xTestGrpRes7575'];};