#!/usr/local/azure/node
// Windows Azure Deployment Tool
// Copyright (C) 2012 Microsoft Corporation

var AzureCli = require('/usr/local/azure/lib/cli');

var cli = new AzureCli();
cli.parse(process.argv);
if (cli.args.length == 0) {
    cli.parse(['', '', '-h']);
}

// Note: this script makes use of a private, local binary of Node 
// instead of using the system-wide installation version.
