#!/usr/local/azure/node
// Microsoft Azure Deployment Tool
// Copyright (c) Microsoft Corporation

process.env.PRECOMPILE_STREAMLINE_FILES = 1

var AutoComplete = require('/usr/local/azure/lib/autocomplete');
//load the autocomplete, so that rest code in the file will not execute 
//till the command gets committed. This gets autocomplete faster
new AutoComplete();

var AzureCli = require('/usr/local/azure/lib/cli');
var Constants = require('/usr/local/azure/lib/util/constants');

if (process.argv[2] !== '--gen') {
  cli = new AzureCli();
  cli.parse(process.argv);
  if (cli.args.length === 0) {
    cli.parse(['', '', '-h']);
  }
} else {
  if (process.argv[3]) {
    cli = new AzureCli(null, null, process.argv[3]);
  } else {
    cli = new AzureCli(null, null, Constants.API_VERSIONS.ARM);
    cli = new AzureCli(null, null, Constants.API_VERSIONS.ASM);
  }
}

// Note: this script makes use of a private, local binary of Node 
// instead of using the system-wide installation version.
