// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '53d9063d-87ae-4ea8-be90-3686c3b8669f',
    name: 'Visual Studio Ultimate with MSDN',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '6e606ece-3a5a-4674-a654-d6b02bc5a51b',
    state: 'Enabled',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_ARM_TEST_LOCATION'] = 'East US 2';
  process.env['AZURE_ARM_TEST_RESOURCE_GROUP'] = 'xplattestadlsrg01';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/53d9063d-87ae-4ea8-be90-3686c3b8669f/resourceGroups/xplattestadls3150/providers/Microsoft.DataLakeStore/accounts/xplattestadls2881?api-version=2015-10-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.DataLakeStore/accounts/xplattestadls2881' under resource group 'xplattestadls3150' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': 'c177a4e9-8e79-4662-afb3-e8d8a7757fed',
  'x-ms-correlation-request-id': 'c177a4e9-8e79-4662-afb3-e8d8a7757fed',
  'x-ms-routing-request-id': 'WESTUS:20160223T045147Z:c177a4e9-8e79-4662-afb3-e8d8a7757fed',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Tue, 23 Feb 2016 04:51:47 GMT',
  connection: 'close',
  'content-length': '171' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/53d9063d-87ae-4ea8-be90-3686c3b8669f/resourceGroups/xplattestadls3150/providers/Microsoft.DataLakeStore/accounts/xplattestadls2881?api-version=2015-10-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.DataLakeStore/accounts/xplattestadls2881' under resource group 'xplattestadls3150' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': 'c177a4e9-8e79-4662-afb3-e8d8a7757fed',
  'x-ms-correlation-request-id': 'c177a4e9-8e79-4662-afb3-e8d8a7757fed',
  'x-ms-routing-request-id': 'WESTUS:20160223T045147Z:c177a4e9-8e79-4662-afb3-e8d8a7757fed',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Tue, 23 Feb 2016 04:51:47 GMT',
  connection: 'close',
  'content-length': '171' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/53d9063d-87ae-4ea8-be90-3686c3b8669f/resourceGroups/xplattestadls3150/providers/Microsoft.DataLakeStore/accounts/xplattestadls2881?api-version=2015-10-01-preview', '*')
  .reply(409, "{\"error\":{\"code\":\"ResourceConflicted\",\"message\":\"Resource Name is belong to another owner.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '93',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': '02847f99-259a-4b29-ac94-ac8a68f14a0b',
  server: 'Microsoft-IIS/8.5',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': '0292e4f2-2be9-4241-a872-28a6548b1788',
  'x-ms-routing-request-id': 'WESTUS:20160223T045149Z:0292e4f2-2be9-4241-a872-28a6548b1788',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Tue, 23 Feb 2016 04:51:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/53d9063d-87ae-4ea8-be90-3686c3b8669f/resourceGroups/xplattestadls3150/providers/Microsoft.DataLakeStore/accounts/xplattestadls2881?api-version=2015-10-01-preview', '*')
  .reply(409, "{\"error\":{\"code\":\"ResourceConflicted\",\"message\":\"Resource Name is belong to another owner.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '93',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': '02847f99-259a-4b29-ac94-ac8a68f14a0b',
  server: 'Microsoft-IIS/8.5',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': '0292e4f2-2be9-4241-a872-28a6548b1788',
  'x-ms-routing-request-id': 'WESTUS:20160223T045149Z:0292e4f2-2be9-4241-a872-28a6548b1788',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Tue, 23 Feb 2016 04:51:48 GMT',
  connection: 'close' });
 return result; }]];